[package]
name = "stdhello"
version = "0.1.0"

[target]
device = "nokia-e52"

[language]
name = "rust-std"

[symbian]
uid3 = "0xe0000693"
capabilities = []
vendor = "symdev"

[signing]
mode = "self-signed"
