//! `StringsResources`: a project's `locales/` as one compiled resource file per
//! language, the way a C++ application ships its `.rls` strings.
//!
//! `default.toml` becomes `<app>_strings.rsc`, and `<language>.toml` becomes
//! `<app>_strings.r<code>`. All of them are installed; at run time
//! `BaflUtils::NearestLanguageFile` picks the one for the device and leaves the `.rsc`
//! when none matches — the platform's own rule, not one written here. The program opens
//! that one file and reads a string when it needs it, so what it holds is one open file
//! and the strings in use, not every language (the C++ model, measured in
//! `docs/research/wip/launcher-locale.md`).
//!
//! # The source
//!
//! Every string is a `BUF8` whose bytes are the value's UTF-8. `BUF8` is never compressed
//! and has no length prefix (`rcomp-spec.md` §3.1), so the resource *is* the UTF-8 and
//! the run time can hand it out as a `&str` with no conversion and no second buffer.
//! Printable ASCII is written literally and every other byte as a `<0xNN>` character
//! literal, which `BUF8` narrows to exactly that byte. U+0000 never reaches here:
//! `symdev-locale` refuses it, because `<0x0000>` is broken in this `rcomp`.
//!
//! There is no `#include`: the file must compile for a console project, which has no
//! reason to have the Avkon headers on its include path, so the signature structure is
//! declared here with the SDK's own layout (`uikon.rh:129`: `LONG signature`, `SRLINK
//! self`; `EEikResourceSignatureValue` is 4 in `uikon.hrh:38`).
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use symdev_core::Artifact;
use symdev_locale::{Language, Locales, Table};

/// One project's strings, in every language it has.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StringsResources {
    /// The executable's name: the files are `<app>_strings.*`, and the run time finds
    /// them from its own file name.
    pub app: String,
    pub locales: Locales,
}

impl StringsResources {
    /// The `.rss` source for one language's table. Keys are compiled in the order
    /// [`Locales::keys`] gives, which is what [`Locales::index`] counts.
    pub fn rss(&self, table: &Table) -> String {
        let mut out = String::from(
            "// Generated by symdev from locales/. Do not edit.\n\
             NAME STRS\n\n\
             STRUCT SYMDEV_SIG { LONG signature = 4; SRLINK self; }\n\
             STRUCT SYMDEV_STR { BUF8 text; }\n\n\
             RESOURCE SYMDEV_SIG { }\n",
        );
        for key in self.locales.keys() {
            let value = table
                .entries
                .get(key)
                .map(String::as_str)
                .unwrap_or_default();
            let _ = writeln!(
                out,
                "RESOURCE SYMDEV_STR {{ text = {}; }} // {key}",
                literal(value)
            );
        }
        out
    }

    /// `build/<app>_strings.rsc` for the default, `…_strings.r<code>` for a language.
    pub fn rsc_path(&self, build_dir: &Path, language: Option<Language>) -> PathBuf {
        build_dir.join(format!("{}_strings.{}", self.app, extension(language)))
    }

    /// `build/<app>_strings_<ext>.rss`: one generated source per language.
    pub fn rss_path(&self, build_dir: &Path, language: Option<Language>) -> PathBuf {
        build_dir.join(format!("{}_strings_{}.rss", self.app, extension(language)))
    }

    /// Where a language's file is installed: beside the application's other resources.
    pub fn dest(&self, language: Option<Language>) -> String {
        format!(
            "!:\\resource\\apps\\{}_strings.{}",
            self.app,
            extension(language)
        )
    }

    /// Every language, the default first, with its table.
    pub fn languages(&self) -> impl Iterator<Item = (Option<Language>, &Table)> {
        std::iter::once((None, &self.locales.default))
            .chain(self.locales.variants.iter().map(|(l, t)| (Some(*l), t)))
    }

    /// Whether there is any string to compile. A `locales/` that only translates the
    /// caption has none, and gets no strings file: an empty one would be installed and
    /// opened for nothing.
    pub fn has_strings(&self) -> bool {
        !self.locales.keys().is_empty()
    }

    /// The compiled files, as installed artifacts — none when there are no strings.
    pub fn artifacts(&self, build_dir: &Path) -> Vec<Artifact> {
        if !self.has_strings() {
            return Vec::new();
        }
        self.languages()
            .map(|(language, _)| {
                Artifact::installed(self.rsc_path(build_dir, language), self.dest(language))
            })
            .collect()
    }
}

fn extension(language: Option<Language>) -> String {
    language.map_or_else(|| "rsc".to_string(), |l| l.suffix())
}

/// A value as `rcomp` source: runs of printable ASCII in quotes, every other byte of
/// its UTF-8 as `<0xNN>`. An empty value is `""`.
fn literal(value: &str) -> String {
    let mut out = String::new();
    let mut quoted = false;
    for &byte in value.as_bytes() {
        let printable = (0x20..0x7f).contains(&byte) && byte != b'"' && byte != b'\\';
        if printable != quoted {
            out.push('"');
            quoted = printable;
        }
        if printable {
            out.push(char::from(byte));
        } else {
            let _ = write!(out, "<0x{byte:02x}>");
        }
    }
    if quoted {
        out.push('"');
    }
    if out.is_empty() {
        out.push_str("\"\"");
    }
    out
}

#[cfg(test)]
mod tests;
