//! `UiResources`: the `.rss` text a GUI application needs, generated from `[ui]`.
//!
//! A Rust project has no `.mmp` and no `data/` directory, so the two resource sources
//! an Avkon application cannot run without are written here and handed to the native
//! preprocessor and resource compiler that the C++ path already uses — the pair
//! experiment 56 verified byte-for-byte against the SDK's `cpp.exe` and `rcomp.exe` on
//! 143 resources. Nothing new encodes a resource; only the text is new.
//!
//! What the fallback `Rsc::registration` cannot do, and why this exists: it writes an
//! `APP_REGISTRATION_INFO` with an **empty** `localisable_resource_file`, which is
//! enough for a console program to be launchable by UID and leaves a GUI application
//! with no caption and no icon in the menu (`avkon-rust-spec.md` §6.2).
use std::path::{Path, PathBuf};

use symdev_core::Artifact;
use symdev_locale::{Language, Locales};
use symdev_manifest::{Softkeys, UiApp};

pub use caption::Caption;

/// The resource set of one GUI application.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UiResources {
    /// The application name: the EXE, the resources and the icon all share it.
    pub app: String,
    pub uid3: u32,
    pub ui: UiApp,
    /// `[symbian] icon`, already joined to the project root, when there is one.
    pub icon: Option<PathBuf>,
    /// The languages `locales/` translates the caption into; each becomes its own
    /// `<app>.r<code>` beside the default `<app>.rsc`.
    pub captions: Vec<Caption>,
}

impl UiResources {
    /// `build/<app>.rss`.
    pub fn app_rss_path(&self, build_dir: &Path) -> PathBuf {
        build_dir.join(format!("{}.rss", self.app))
    }

    /// `build/<app>_reg.rss`.
    pub fn reg_rss_path(&self, build_dir: &Path) -> PathBuf {
        build_dir.join(format!("{}_reg.rss", self.app))
    }

    pub fn app_rsc_path(&self, build_dir: &Path) -> PathBuf {
        build_dir.join(format!("{}.rsc", self.app))
    }

    pub fn reg_rsc_path(&self, build_dir: &Path) -> PathBuf {
        build_dir.join(format!("{}_reg.rsc", self.app))
    }

    /// `build/<app>.rsg`, the `#define R_APP_LOCALISABLE_APP_INFO` the registration
    /// resource includes. It is a build input, not an installed file.
    pub fn rsg_path(&self, build_dir: &Path) -> PathBuf {
        build_dir.join(format!("{}.rsg", self.app))
    }

    /// Where the localisable resource is installed, and what `_reg.rss` points at.
    pub fn app_rsc_dest(&self) -> String {
        format!("!:\\resource\\apps\\{}.rsc", self.app)
    }

    /// `\private\10003a3f\import\apps\`: where the application architecture server
    /// reads a registration from, whatever the `.mmp` of a C++ project says.
    pub fn reg_rsc_dest(&self) -> String {
        format!("!:\\private\\10003a3f\\import\\apps\\{}_reg.rsc", self.app)
    }

    /// The application resource: the caption, the softkeys and the icon.
    ///
    /// Written after `examples/gui/data/gui.rss`, which installs and runs. The
    /// `RSS_SIGNATURE` and the empty `TBUF` are what `eikcore` expects at resource ids
    /// 1 and 2; `EIK_APP_INFO` is id 3 and `LOCALISABLE_APP_INFO` is named, so the
    /// `.rsg` can give the registration resource its id.
    pub fn app_rss(&self) -> String {
        let mut out = String::new();
        out.push_str(
            "// Generated by symdev from [ui] in symdev.toml. Do not edit.\n\
             NAME APPR\n\n\
             #include <eikon.rh>\n\
             #include <eikon.hrh>\n\
             #include <avkon.rh>\n\
             #include <avkon.hrh>\n\
             #include <appinfo.rh>\n\n\
             RESOURCE RSS_SIGNATURE { }\n\n\
             RESOURCE TBUF { buf = \"\"; }\n\n\
             RESOURCE EIK_APP_INFO\n    {\n",
        );
        // `menubar` and `cba` are forward references to resources further down this
        // file; `rcomp` resolves them, which is how every S60 application's `.rss` is
        // written (`EIK_APP_INFO` has to stay the third resource).
        // The menu bar and the Options softkey are emitted together or not at all.
        // That pair is the whole of what experiment 91 found: `EAknSoftkeyOptions`
        // with no `menubar` here makes the framework dereference a menu bar that does
        // not exist, and the application dies with an access violation. The manifest
        // used to refuse the combination; now it cannot be written down.
        if self.has_menu() {
            out.push_str("    menubar = r_symrs_menubar;\n");
        }
        out.push_str("    cba = r_symrs_cba;\n    }\n\n");
        out.push_str(&self.cba_rss());
        if self.has_menu() {
            out.push_str(&self.menu_rss());
        }
        out.push_str(&format!(
            "RESOURCE LOCALISABLE_APP_INFO r_app_localisable_app_info\n    \
             {{\n    short_caption = \"{}\";\n    \
             caption_and_icon = CAPTION_AND_ICON_INFO\n        \
             {{\n        caption = \"{}\";\n",
            rss_string(&self.ui.short_caption),
            rss_string(&self.ui.caption)
        ));
        // `number_of_icons = 0` and no `icon_file` when the manifest names no icon:
        // an `icon_file` pointing at a `.mif` the package does not carry is how an
        // application ends up with a blank square in the menu.
        match &self.icon {
            Some(_) => out.push_str(&format!(
                "        number_of_icons = 1;\n        \
                 icon_file = \"\\\\resource\\\\apps\\\\{}_aif.mif\";\n",
                self.app
            )),
            None => out.push_str("        number_of_icons = 0;\n"),
        }
        out.push_str("        };\n    }\n");
        out
    }

    /// The button group, generated here rather than named from Avkon's own `.rsg`.
    ///
    /// This is the fix for the softkey that did nothing for three sessions. The
    /// softkeys were always delivered — the CBA turned F2 into a call to
    /// `HandleCommandL` — but with `cba = R_AVKON_SOFTKEYS_EXIT` the command that
    /// arrived on this ROM was **3001** (`EAknSoftkeyBack`), not the `EAknSoftkeyExit`
    /// the shim compared against, and the shim's constant was wrong as well
    /// (`avkon.hrh` puts `EAknSoftkeyExit` at 3009, not 3002). Owning the resource
    /// removes both halves of the problem: the id on the right button is
    /// `EEikCmdExit`, which is the command the shim has always handled, and the id on
    /// the left is `EAknSoftkeyOptions`, which is what the framework itself watches
    /// for to open the menu bar.
    fn cba_rss(&self) -> String {
        let left = match self.ui.softkeys {
            // No menu, so nothing for the left button to do. `EAknSoftkeyEmpty` is
            // Avkon's own name for "this button does nothing"; the framework does not
            // act on it and the shim forwards it like any other command.
            Softkeys::Exit => ("EAknSoftkeyEmpty".to_string(), String::new()),
            Softkeys::OptionsExit => (
                "EAknSoftkeyOptions".to_string(),
                rss_string(&self.ui.left_softkey),
            ),
        };
        format!(
            "RESOURCE CBA r_symrs_cba\n    \
             {{\n    buttons =\n        {{\n        \
             CBA_BUTTON {{ id = {}; txt = \"{}\"; }},\n        \
             CBA_BUTTON {{ id = EEikCmdExit; txt = \"{}\"; }}\n        \
             }};\n    }}\n\n",
            left.0,
            left.1,
            rss_string(&self.ui.right_softkey)
        )
    }

    /// Whether this application has an Options menu at all, which is the same
    /// question as whether its left softkey opens one.
    fn has_menu(&self) -> bool {
        self.ui.softkeys == Softkeys::OptionsExit
    }

    /// The Options menu: one `MENU_BAR` with one `MENU_TITLE`, and an **empty**
    /// `MENU_PANE`.
    ///
    /// Empty on purpose. The lines are not in the manifest and not in any resource:
    /// the application declares them in Rust and the shim adds them with
    /// `CEikMenuPane::AddMenuItemL` from `DynInitMenuPaneL`, each time the menu opens
    /// (`eikmenup.h:456`, experiment 95). What still has to be compiled is the pane
    /// itself, because nothing calls `DynInitMenuPaneL` for a menu bar that has no
    /// pane to show.
    fn menu_rss(&self) -> String {
        format!(
            "RESOURCE MENU_BAR r_symrs_menubar\n    \
             {{\n    titles =\n        {{\n        \
             MENU_TITLE {{ menu_pane = r_symrs_menupane; txt = \"{}\"; }}\n        \
             }};\n    }}\n\n\
             RESOURCE MENU_PANE r_symrs_menupane\n    \
             {{\n    items =\n        {{\n        }};\n    }}\n\n",
            rss_string(&self.ui.left_softkey)
        )
    }

    /// The registration resource, with the two fields the generated fallback cannot
    /// fill: where the localisable resource is installed, and which resource in it.
    pub fn reg_rss(&self) -> String {
        format!(
            "// Generated by symdev from [ui] in symdev.toml. Do not edit.\n\
             #include <appinfo.rh>\n\
             #include <{app}.rsg>\n\n\
             UID2 KUidAppRegistrationResourceFile\n\
             UID3 0x{uid3:08x}\n\n\
             RESOURCE APP_REGISTRATION_INFO\n    \
             {{\n    \
             app_file = \"{app}\";\n    \
             localisable_resource_file = \"\\\\resource\\\\apps\\\\{app}\";\n    \
             localisable_resource_id = R_APP_LOCALISABLE_APP_INFO;\n    \
             }}\n",
            app = self.app,
            uid3 = self.uid3
        )
    }

    /// The compiled resources, as installed files: the application resource, one per
    /// translated caption, and the registration.
    pub fn artifacts(&self, build_dir: &Path) -> Vec<Artifact> {
        let mut out = vec![Artifact::installed(
            self.app_rsc_path(build_dir),
            self.app_rsc_dest(),
        )];
        for c in &self.captions {
            out.push(Artifact::installed(
                self.app_rsc_variant_path(build_dir, c.language),
                self.app_rsc_variant_dest(c.language),
            ));
        }
        out.push(Artifact::installed(
            self.reg_rsc_path(build_dir),
            self.reg_rsc_dest(),
        ));
        out
    }

    /// Takes the caption translations from `locales/`, when the project has one.
    pub fn with_locales(mut self, locales: Option<&Locales>) -> Self {
        self.captions = Caption::of(&self.ui, locales);
        self
    }

    /// The same application with `caption`'s pair in place of the manifest's: the
    /// source of `<app>.r<code>`, which differs from `<app>.rsc` in nothing else.
    pub fn variant(&self, caption: &Caption) -> UiResources {
        let mut v = self.clone();
        v.ui.caption = caption.caption.clone();
        v.ui.short_caption = caption.short_caption.clone();
        v
    }

    /// `build/<app>.r<code>`.
    pub fn app_rsc_variant_path(&self, build_dir: &Path, language: Language) -> PathBuf {
        build_dir.join(format!("{}.{}", self.app, language.suffix()))
    }

    /// `!:\resource\apps\<app>.r<code>`, beside the `.rsc` whose name
    /// `localisable_resource_file` gives without an extension — the launcher adds the
    /// nearest one for the device's language.
    pub fn app_rsc_variant_dest(&self, language: Language) -> String {
        format!("!:\\resource\\apps\\{}.{}", self.app, language.suffix())
    }
}

/// A caption inside an `.rss` string literal. The resource compiler reads `\` as an
/// escape and `"` as the end of the literal, so both are escaped; a caption is text a
/// person wrote in the manifest and may hold either.
fn rss_string(text: &str) -> String {
    text.replace('\\', "\\\\").replace('"', "\\\"")
}

mod caption;
#[cfg(test)]
mod tests;
