//! `UiResources`: the `.rss` text a GUI application needs, generated from `[ui]`.
//!
//! A Rust project has no `.mmp` and no `data/` directory, so the two resource sources
//! an Avkon application cannot run without are written here and handed to the native
//! preprocessor and resource compiler that the C++ path already uses — the pair
//! experiment 56 verified byte-for-byte against the SDK's `cpp.exe` and `rcomp.exe` on
//! 143 resources. Nothing new encodes a resource; only the text is new.
//!
//! What the fallback `Rsc::registration` cannot do, and why this exists: it writes an
//! `APP_REGISTRATION_INFO` with an **empty** `localisable_resource_file`, which is
//! enough for a console program to be launchable by UID and leaves a GUI application
//! with no caption and no icon in the menu (`avkon-rust-spec.md` §6.2).
use std::path::{Path, PathBuf};

use symdev_core::Artifact;
use symdev_manifest::UiApp;

/// The resource set of one GUI application.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UiResources {
    /// The application name: the EXE, the resources and the icon all share it.
    pub app: String,
    pub uid3: u32,
    pub ui: UiApp,
    /// `[symbian] icon`, already joined to the project root, when there is one.
    pub icon: Option<PathBuf>,
}

impl UiResources {
    /// `build/<app>.rss`.
    pub fn app_rss_path(&self, build_dir: &Path) -> PathBuf {
        build_dir.join(format!("{}.rss", self.app))
    }

    /// `build/<app>_reg.rss`.
    pub fn reg_rss_path(&self, build_dir: &Path) -> PathBuf {
        build_dir.join(format!("{}_reg.rss", self.app))
    }

    pub fn app_rsc_path(&self, build_dir: &Path) -> PathBuf {
        build_dir.join(format!("{}.rsc", self.app))
    }

    pub fn reg_rsc_path(&self, build_dir: &Path) -> PathBuf {
        build_dir.join(format!("{}_reg.rsc", self.app))
    }

    /// `build/<app>.rsg`, the `#define R_APP_LOCALISABLE_APP_INFO` the registration
    /// resource includes. It is a build input, not an installed file.
    pub fn rsg_path(&self, build_dir: &Path) -> PathBuf {
        build_dir.join(format!("{}.rsg", self.app))
    }

    /// Where the localisable resource is installed, and what `_reg.rss` points at.
    pub fn app_rsc_dest(&self) -> String {
        format!("!:\\resource\\apps\\{}.rsc", self.app)
    }

    /// `\private\10003a3f\import\apps\`: where the application architecture server
    /// reads a registration from, whatever the `.mmp` of a C++ project says.
    pub fn reg_rsc_dest(&self) -> String {
        format!("!:\\private\\10003a3f\\import\\apps\\{}_reg.rsc", self.app)
    }

    /// The application resource: the caption, the softkeys and the icon.
    ///
    /// Written after `examples/gui/data/gui.rss`, which installs and runs. The
    /// `RSS_SIGNATURE` and the empty `TBUF` are what `eikcore` expects at resource ids
    /// 1 and 2; `EIK_APP_INFO` is id 3 and `LOCALISABLE_APP_INFO` is named, so the
    /// `.rsg` can give the registration resource its id.
    pub fn app_rss(&self) -> String {
        let mut out = String::new();
        out.push_str(&format!(
            "// Generated by symdev from [ui] in symdev.toml. Do not edit.\n\
             NAME APPR\n\n\
             #include <eikon.rh>\n\
             #include <avkon.rh>\n\
             #include <avkon.rsg>\n\
             #include <appinfo.rh>\n\n\
             RESOURCE RSS_SIGNATURE {{ }}\n\n\
             RESOURCE TBUF {{ buf = \"\"; }}\n\n\
             RESOURCE EIK_APP_INFO\n    \
             {{\n    cba = {};\n    }}\n\n",
            self.ui.softkeys.resource()
        ));
        out.push_str(&format!(
            "RESOURCE LOCALISABLE_APP_INFO r_app_localisable_app_info\n    \
             {{\n    short_caption = \"{}\";\n    \
             caption_and_icon = CAPTION_AND_ICON_INFO\n        \
             {{\n        caption = \"{}\";\n",
            rss_string(&self.ui.short_caption),
            rss_string(&self.ui.caption)
        ));
        // `number_of_icons = 0` and no `icon_file` when the manifest names no icon:
        // an `icon_file` pointing at a `.mif` the package does not carry is how an
        // application ends up with a blank square in the menu.
        match &self.icon {
            Some(_) => out.push_str(&format!(
                "        number_of_icons = 1;\n        \
                 icon_file = \"\\\\resource\\\\apps\\\\{}_aif.mif\";\n",
                self.app
            )),
            None => out.push_str("        number_of_icons = 0;\n"),
        }
        out.push_str("        };\n    }\n");
        out
    }

    /// The registration resource, with the two fields the generated fallback cannot
    /// fill: where the localisable resource is installed, and which resource in it.
    pub fn reg_rss(&self) -> String {
        format!(
            "// Generated by symdev from [ui] in symdev.toml. Do not edit.\n\
             #include <appinfo.rh>\n\
             #include <{app}.rsg>\n\n\
             UID2 KUidAppRegistrationResourceFile\n\
             UID3 0x{uid3:08x}\n\n\
             RESOURCE APP_REGISTRATION_INFO\n    \
             {{\n    \
             app_file = \"{app}\";\n    \
             localisable_resource_file = \"\\\\resource\\\\apps\\\\{app}\";\n    \
             localisable_resource_id = R_APP_LOCALISABLE_APP_INFO;\n    \
             }}\n",
            app = self.app,
            uid3 = self.uid3
        )
    }

    /// The two compiled resources, as installed files.
    pub fn artifacts(&self, build_dir: &Path) -> Vec<Artifact> {
        vec![
            Artifact::installed(self.app_rsc_path(build_dir), self.app_rsc_dest()),
            Artifact::installed(self.reg_rsc_path(build_dir), self.reg_rsc_dest()),
        ]
    }
}

/// A caption inside an `.rss` string literal. The resource compiler reads `\` as an
/// escape and `"` as the end of the literal, so both are escaped; a caption is text a
/// person wrote in the manifest and may hold either.
fn rss_string(text: &str) -> String {
    text.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests;
