[package]
name = "symdev-build"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
symdev-core = { path = "../symdev-core" }
symdev-sis = { path = "../symdev-sis" }
symdev-makekeys = { path = "../symdev-makekeys" }
symdev-uidcrc = { path = "../symdev-uidcrc" }
symdev-rcomp = { path = "../symdev-rcomp" }
symdev-elf2e32 = { path = "../symdev-elf2e32" }
thiserror = "2"

[dev-dependencies]
tempfile = "3"
der = { version = "0.7", features = ["alloc", "pem"] }
x509-cert = "0.2"
