[package]
name = "symdev-build"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
symdev-core = { path = "../symdev-core" }
thiserror = "2"
flate2 = { version = "1", default-features = false, features = ["zlib"] }
sha1 = "0.10"
dsa = "0.6"
x509-cert = "0.2"
der = { version = "0.7", features = ["derive", "alloc"] }
des = "0.8"
cbc = { version = "0.1", features = ["alloc"] }
md-5 = "0.10"
rand = "0.8"

[dev-dependencies]
tempfile = "3"
