[package]
name = "helloraw"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
# `src/main.rs` is a library: rustc never links, symdev does (design spec §3).
autobins = false

[lib]
path = "src/main.rs"
crate-type = ["staticlib"]

[dependencies]
symbian-runtime = { path = "../../crates/symbian-runtime" }
symbian-std = { path = "../../crates/symbian-std" }
