[package]
name = "netdemo"
version = "0.1.0"

[target]
device = "nokia-e52"

[language]
name = "rust"

[symbian]
uid3 = "0xe0000686"
capabilities = ["NetworkServices"]
vendor = "symdev"

[signing]
mode = "self-signed"
