//! `GcceCompat`: the generated header that repairs `gcce.h`'s varargs macros.
use std::path::{Path, PathBuf};

use symdev_core::{Error, Result};

/// A symdev-generated header force-included straight after the SDK's
/// `epoc32/include/gcce/gcce.h`, repairing that header's varargs macros for an AAPCS
/// GCC. Written into the build directory on every build; never part of a user project.
pub struct GcceCompat {
    header: PathBuf,
}

impl GcceCompat {
    const NAME: &str = "symdev-gcce-compat.h";

    /// Write the header into `build_dir` and return it.
    pub fn ensure(build_dir: &Path) -> Result<Self> {
        let header = build_dir.join(Self::NAME);
        std::fs::write(&header, Self::SOURCE)
            .map_err(|e| Error::Other(format!("write {header:?}: {e}")))?;
        Ok(Self { header })
    }

    pub fn header(&self) -> &Path {
        &self.header
    }

    pub const SOURCE: &str = r#"/* Generated by symdev. Do not edit: rewritten on every build.
 *
 * The SDK force-includes epoc32/include/gcce/gcce.h into every translation unit.
 * That header declares the Symbian varargs type as its own one-word struct and
 * then hands the *member* to the compiler builtin:
 *
 *     typedef struct __va_list { void *__ap; } va_list;   // in namespace std for C++
 *     #define va_start(ap, parmN) __builtin_va_start(ap.__ap, parmN)
 *
 * That is only correct for a compiler whose __builtin_va_list is itself a bare
 * void *, which is what the SDK's GCCE 3.4.3 had. On an AAPCS GCC (this
 * toolchain: GCC 12.1.0 arm-none-symbianelf) __builtin_va_list is
 * struct __va_list { void *__ap; }, so the builtins want a __va_list lvalue and
 * every varargs function fails ("invalid initialization of reference of type
 * '__va_list&' from expression of type 'void*'", or in C "first argument to
 * 'va_arg' not of type 'va_list'").
 *
 * The three macros below re-point the builtins at the whole ap object, viewed as
 * the compiler's own va_list. gcce.h's VA_START/VA_ARG/VA_END expand to these at
 * the point of use, so they are repaired too.
 *
 * This deliberately does NOT redefine the va_list / VA_LIST type. VA_LIST is part
 * of the published Symbian API (TDes16::FormatList, TDes16::AppendFormatList,
 * Kern::Printf), and euser.dso exports it as
 * _ZN6TDes1610FormatListERK7TDesC16St9__va_list -- std::__va_list, the typedef
 * gcce.h declares. Leaving the typedef alone leaves that name, the 4-byte
 * one-pointer layout and the argument passing exactly as the SDK libraries
 * expect; only the macro bodies change. See docs/research/experiment-backlog.md
 * experiment 59.
 */
#undef va_start
#undef va_arg
#undef va_end
#define va_start(ap, parmN) __builtin_va_start(*(__builtin_va_list *)&(ap), parmN)
#define va_arg(ap, type) __builtin_va_arg(*(__builtin_va_list *)&(ap), type)
#define va_end(ap) __builtin_va_end(*(__builtin_va_list *)&(ap))
"#;
}
