[package]
name = "allocdemo"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "allocdemo"
path = "src/main.rs"
test = false

[dependencies]
symbian-core = { path = "../../crates/symbian-core" }
symbian-std = { path = "../../crates/symbian-std" }
