[package]
name = "gui"
version = "0.1.0"

[target]
device = "nokia-e52"

[language]
name = "cpp"

[symbian]
uid3 = "0xe7351c20"
capabilities = []
vendor = "symdev"
icon = "gfx/gui.svg"

[signing]
mode = "self-signed"
