//! Localised strings, the way a C++ application reads its `.rls` strings — one compiled
//! resource file per language, the nearest one opened once, each string read when it is
//! asked for — and the device's UI language.
//!
//! - [`Str`] and [`Text`]: a key of the project's `locales/`, and the string it reads.
//!   An application writes `symbian_std::strings!()` and gets one `Str` constant per key
//!   (see `strings.rs` for the file, the shim and the measured cost).
//! - [`Language`]: what the device is set to, for a program that wants to know. The
//!   choice of file does not need it: `BaflUtils::NearestLanguageFile` makes it, with the
//!   platform's own fallback rules — including `TLocale::LanguageDowngrade`, which a
//!   Rust-side chain never implemented.
//!
//! The launcher caption is localised by the same mechanism on the build side:
//! `<app>.r<code>` beside `<app>.rsc`, generated by symdev from `locales/`.
mod language;
mod layout;
mod strings;
mod text;

pub use language::Language;
pub use strings::Str;
pub use text::Text;
