[package]
name = "shimdemo"
version = "0.1.0"

[target]
device = "nokia-e52"

[language]
name = "rust"

[symbian]
uid3 = "0xe0000684"
capabilities = []
vendor = "symdev"

[signing]
mode = "self-signed"
