[package]
name = "symdev-makekeys"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "makekeys"
path = "src/bin/makekeys.rs"

[dependencies]
symdev-core = { path = "../symdev-core" }
sha1 = "0.10"
dsa = "0.6"
pkcs8 = { version = "0.10", default-features = false, features = ["alloc", "pem"] }
x509-cert = "0.3"
der = { version = "0.7", features = ["derive", "alloc", "pem"] }
rand = "0.8"
