//! The multi-bitmap file store and its `.mbg` header
//! ([bmconv-spec.md](../../../docs/research/bmconv-spec.md) §5, §9).

use symdev_core::{Error, Result};

use crate::depth::MbmDepth;

/// One bitmap of an `.mbm`: its size, depth and stored data.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MbmBitmap {
    pub width: u32,
    pub height: u32,
    pub twips: (u32, u32),
    pub depth: MbmDepth,
    /// Pixel data, compressed as `compression` says.
    pub data: Vec<u8>,
    pub compression: u32,
}

impl MbmBitmap {
    const HEADER: u32 = 40;

    fn bytes(&self) -> Vec<u8> {
        let mut out = Vec::with_capacity(Self::HEADER as usize + self.data.len());
        for word in [
            Self::HEADER + self.data.len() as u32,
            Self::HEADER,
            self.width,
            self.height,
            self.twips.0,
            self.twips.1,
            self.depth.bits(),
            u32::from(self.depth.is_colour()),
            0,
            self.compression,
        ] {
            out.extend_from_slice(&word.to_le_bytes());
        }
        out.extend_from_slice(&self.data);
        out
    }
}

/// An `.mbm` file store.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MbmFile {
    pub bitmaps: Vec<MbmBitmap>,
}

impl MbmFile {
    const UID1: u32 = 0x1000_0037;
    const UID2: u32 = 0x1000_0042;
    /// The tool writes this checksum unconditionally and rejects any other.
    const UID_CHECKSUM: u32 = 0x4739_6439;
    const DATA_START: u32 = 20;

    pub fn new(bitmaps: Vec<MbmBitmap>) -> Self {
        Self { bitmaps }
    }

    pub fn bytes(&self) -> Result<Vec<u8>> {
        if self.bitmaps.is_empty() {
            return Err(Error::Other("MBM without bitmaps".into()));
        }
        let blocks: Vec<Vec<u8>> = self.bitmaps.iter().map(MbmBitmap::bytes).collect();
        let total: usize = blocks.iter().map(Vec::len).sum();
        let table = Self::DATA_START + total as u32;
        let mut out = Vec::with_capacity(table as usize + 4 + 4 * blocks.len());
        for word in [Self::UID1, Self::UID2, 0, Self::UID_CHECKSUM, table] {
            out.extend_from_slice(&word.to_le_bytes());
        }
        let mut offsets = Vec::with_capacity(blocks.len());
        for block in &blocks {
            offsets.push(out.len() as u32);
            out.extend_from_slice(block);
        }
        out.extend_from_slice(&(blocks.len() as u32).to_le_bytes());
        for offset in offsets {
            out.extend_from_slice(&offset.to_le_bytes());
        }
        Ok(out)
    }

    /// `bmconv /h`: the enum named after the header file, one enumerator per
    /// bitmap in source order, CRLF throughout (spec §9.2).
    pub fn mbg_text(&self, header_name: &str, sources: &[String]) -> String {
        let file = header_name.rsplit('\\').next().unwrap_or(header_name);
        let stem = Self::stem(header_name);
        let mut out = format!(
            "// {file}\r\n// Generated by BitmapCompiler\r\n\
             // Copyright (c) 1998-2001 Symbian Ltd.  All rights reserved.\r\n//\r\n\r\n\
             enum TMbm{stem}\r\n\t{{\r\n"
        );
        for (i, source) in sources.iter().enumerate() {
            let comma = if i + 1 == sources.len() { "" } else { "," };
            out.push_str(&format!("\tEMbm{stem}{}{comma}\r\n", Self::stem(source)));
        }
        out.push_str("\t};\r\n");
        out
    }

    /// File name without its directory and last extension, first character
    /// upper case and the rest lower case.
    fn stem(name: &str) -> String {
        let name = name.rsplit(['/', '\\']).next().unwrap_or(name);
        let stem = name.rsplit_once('.').map_or(name, |(head, _)| head);
        let mut chars = stem.chars();
        match chars.next() {
            Some(first) => first
                .to_uppercase()
                .chain(chars.flat_map(char::to_lowercase))
                .collect(),
            None => String::new(),
        }
    }
}
