[package]
name = "symbian-runtime"
version.workspace = true
edition.workspace = true
description = "The E32 process entry point and panic handler for Rust applications on Symbian OS 9.3"

[lib]
crate-type = ["rlib"]

[dependencies]
symbian-alloc = { path = "../symbian-alloc" }
symbian-core = { path = "../symbian-core" }
symbian-sys = { path = "../symbian-sys" }
